server:
  port: 8080
spring:
  application:
    name: spring-boot-mongodb
  data:
    mongodb:
#      database: batches
#      host: cluster0.bexczee.mongodb.net
#      port: 27017
#      username: root
#      password: root
      uri: mongodb+srv://root:root@cluster0.r1nrje4.mongodb.net/batches?retryWrites=true&w=majority
logging:
  level:
    root: WARN
    org.springframework.web: WARN
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG # to see the mongodb queries
    in.stackroute.ust: DEBUG