FROM openjdk:11

WORKDIR usr/src

ADD ./target/topjob_authentication-0.0.1-SNAPSHOT.jar /usr/src/topjob_authentication-0.0.1-SNAPSHOT.jar

ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=dockersqlpassword
ENV MYSQL_ROOT_PASSWORD=dockersqlpassword

ENTRYPOINT ["java","-jar","topjob_authentication-0.0.1-SNAPSHOT.jar"]