# Configuration file for authors-service
spring:
  application:
    name: authors-service
  datasource:
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:27017/author
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true