server:
  port: 9010

spring:
  application:
    name: "Gateway"
  cloud:
    gateway:
      routes:
      - id: authenticator_service
        uri: http://localhost:9000
        predicates:        - Path=/user/**
      - id: Employer
        uri: http://localhost:8082
        predicates:
        - Path=/employer/**
      - id: job
        uri: http://localhost:9096
        predicates:
        - Path=/job/**
      - id: JobSeeker
        uri: http://localhost:8083
        predicates:
        - Path=/jobSeeker/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
            - POST
            - PUT
            - GET
            - DELETE