spring:
  application:
    name: spring-boot-exception-handling
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: false # To show SQL queries
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false
server:
  port: 8080
debug: false
logging:
  logback:
    rollingpolicy:
      max-file-size: 1MB
  file:
    name: application.debug.log
    path: logs
  level:
    org.springframework.web: WARN
    org.hibernate.SQL: DEBUG
    org.hibernate.type: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    in.stackroute.ust: DEBUG
