FROM openjdk:11

WORKDIR usr/src

ADD ./target/JobSeeker-0.0.1-SNAPSHOT.jar /usr/src/JobSeeker-0.0.1-SNAPSHOT.jar

ENV MONGO_HOST=localhost
ENV MONGO_PORT=27017

ENTRYPOINT ["java","-jar","JobSeeker-0.0.1-SNAPSHOT.jar"]