server:
  port: 8080
spring:
  application:
    name: MC1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/user?createDatabaseIfNotExist=true
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true