FROM openjdk:11

WORKDIR usr/src

ADD ./target/job-0.0.1-SNAPSHOT.jar /usr/src/job-0.0.1-SNAPSHOT.jar

ENV MONGO_HOST=localhost
ENV MONGO_PORT=27017

ENTRYPOINT ["java","-jar","job-0.0.1-SNAPSHOT.jar"]